#!/bin/bash
cat Best School > \*\\'"Best School"\'\\*$\?\*\*\*\*\*\:) \#!/bin/bash
cat Best School > \*\\'"Best School"\'\\*$\?\*\*\*\*\*\:) \#!/bin/bash
cat Best School > \*\\'"Best School"\'\\*$\?\*\*\*\*\*\:) \#!/bin/bash
cat Best School > \*\\'"Best School"\'\\*$\?\*\*\*\*\*\:) \#!/bin/bash
cat Best School > \*\\'"Best School"\'\\*$\?\*\*\*\*\*\:) \#!/bin/bash
cat Best School > \*\\'"Best School"\'\\*$\?\*\*\*\*\*\:) \#!/bin/bash
cat Best School > \*\\'"Best School"\'\\*$\?\*\*\*\*\*\:) \#!/bin/bash
cat Best School > \*\\'"Best School"\'\\*$\?\*\*\*\*\*\:) \#!/bin/bash
cat Best School > \*\\'"Best School"\'\\*$\?\*\*\*\*\*\:) \
